title: ThinkingLabs
description: Consulting in Continuous Integration and Continuous Delivery
url: https://thinkinglabs.io
author: Thierry de Pauw
collections:
  talks:
    title: Talk
    output: true
  notes:
    title: Note
    output: true
defaults:
  -
    scope:
      path: ""
      type: "talks"
    values:
      new_layout: false
plugins:
  - jekyll-redirect-from
